return {
  [[                                                                                                ez                         ]],
  [[                                                          A                                   qr                           ]],
  [[                                                          A                                 x3                             ]],
  [[                                                          A                                D                               ]],
  [[                                                          A                              A                                 ]],
  [[                                                          A                            A                                   ]],
  [[                                                          A                          Aw                                    ]],
  [[                                                          A             C          Ae                                      ]],
  [[                                 c                 e      A            A         AO                                        ]],
  [[                                  yi               z      A           A        AA                                          ]],
  [[                                    pn              A     A         zA       EA                                            ]],
  [[                                      0n      w      L    A R  4   jB      JAz                                             ]],
  [[                                        Rq      C    1y y AzC zD  ND     UAo                                               ]],
  [[                                          Dq     Lz   A iwAwA Az AR    dAV                                                 ]],
  [[                                            Aw    wA   AAvArA3AzAW   tAA                                                   ]],
  [[                                              At E  AAAUrCrAyAAAo  zAA                                                     ]],
  [[                                            tR  AxxA  A AA JAACAz AA                                                       ]],
  [[                                              zAszAxgF9AxAAGxuBAzAwyA    yAp                                               ]],
  [[                                               wAxsBmAzsAoDBqxCAEnAtjAfAAz                                                 ]],
  [[                                         zrNACLbyAyBEVCcAxEA7 EFsATTdAgAbAj                                                ]],
  [[                                          2ly AAAAyBAAtA0     zAyCAABJtGJpAI                                               ]],
  [[                                    uttvvwwyNzAiAAtAAAAN        yAABBB Ahhzzzzzzzzzzzzzzzzzyxxwwvvtroje952ZXURRNJINWb      ]],
  [[           ztqkfb92RNKHDAAAAAAAAAAAAAAAAAAAAAAAAzAABHJYa          zAkFMAkoswT                                              ]],
  [[                                          sVAAA6 zzAyNQA       3dAAAADAykakyFAZ                                            ]],
  [[                                             yAwBnoaoAzA AwGzBAzAA AAzFA0u                                                 ]],
  [[                                               PAk4AtA1ItaAzIwAzAwzyAxC0 MAD                                               ]],
  [[                                              A8 xA ABl12aAzAAH2AzA AA  uQ  zAAu                                           ]],
  [[                                           JY    5K   A wvsmAIpbRND A AC        jA4                                        ]],
  [[                                         i     1R    Ar ZZuINA AloIHC   hAz        zFB                                     ]],
  [[                                             U5     64 2  pAOfM Az   OL    Ah          yAt                                 ]],
  [[                                           Ll       G  d  sAru Q Az    SP    aA            L1                              ]],
  [[                                         Hp        A      yA Y   zA             A             yD                           ]],
  [[                                       By         u       zA F     A              Xh              Nv                       ]],
  [[                                     Bz                    B A     yA                                                      ]],
  [[                                   A                       C        vA                                                     ]],
  [[                                 A                         D         pF                                                    ]],
  [[                               A                           G          gU                                                   ]],
  [[                             C                             J           8b                                                  ]],
  [[                           F                               K            7q                                                 ]],
  [[                                                           K             Uy                                                ]],
  [[                                                           f              Hz                                               ]],
  [[                                                                           Gz                                              ]],
}
